# Basic set up for three package managers

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/cli
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/core
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/crypto
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/web-ui
    schedule:
      interval: daily
